### ISSUE TITLE
Create Mockup for the App.

### ISSUE THREAD

**Issue by ellipe** [ellipe/patients_ui#2]
Basic mockup of the different pages and element inside them.
**BaseLayout**
![layout](https://user-images.githubusercontent.com/5317427/30983860-43b53e8a-a451-11e7-81bc-aeb84762e726.png)

**LoginPage**
![login page](https://user-images.githubusercontent.com/5317427/30983875-51bed00e-a451-11e7-821c-adfcb40d31dd.png)

**HomePage**
![home page](https://user-images.githubusercontent.com/5317427/30983831-2b7d9ba0-a451-11e7-931a-6d36451af6b7.png)

**ResultPage**
![result page](https://user-images.githubusercontent.com/5317427/30983876-52dd13e2-a451-11e7-83c2-4c098284e644.png)

**GraphPage**
![graph page](https://user-images.githubusercontent.com/5317427/30988229-484b9b2a-a45f-11e7-833e-68b019384017.png)

**Comment by Jaime691** [comment]
Add a month filter above the search box.

**Comment by ellipe** [comment]
OrderCard Component must have the following data in it:
- ClinicalHistory
- Physician
- ServiceLocation
- ¿Empresa?
- Phone Number
- Consultorio 
- PhysicianOffice
- Bed
